create table if not exists public.stall_registrations (
  id bigint generated by default as identity primary key,
  full_name text not null,
  cpf_cnpj text not null,
  email text not null,
  phone text not null,
  business_name text not null,
  fair_name text not null,
  region text not null,
  category text not null,
  booth_location text,
  description text not null,
  days_hours text,
  consent_given integer not null default 1,
  status text not null default 'received' check (status in ('received','reviewing','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.stall_registrations enable row level security;

-- Não crie políticas públicas de INSERT.
-- O servidor Node usa a SERVICE_ROLE_KEY, que fica somente no arquivo .env do servidor.
