-- Execute este SQL no Supabase SQL Editor.
-- A senha nunca deve ser salva em texto puro.
create table if not exists public.admin_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

-- Não crie políticas públicas. O painel acessa esta tabela usando a service role key somente no servidor.

-- 1) Gere um hash localmente:
--    npm run admin:hash -- SuaSenhaForte
-- 2) Cole o resultado abaixo no lugar de COLE_HASH_GERADO_AQUI.
insert into public.admin_users (username, password_hash, active)
values ('admin', 'COLE_HASH_GERADO_AQUI', true)
on conflict (username) do update set
  password_hash = excluded.password_hash,
  active = excluded.active,
  updated_at = now();
