create table if not exists public.fairs (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  region text not null,
  address text,
  days_hours text,
  contact_name text,
  contact_phone text,
  contact_email text,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists fairs_status_idx on public.fairs(status);
create index if not exists fairs_region_idx on public.fairs(region);

alter table public.fairs enable row level security;


-- atualizacao tabela

alter table public.fairs
add column if not exists photo_url text;

-- Cria o bucket usado para guardar as fotos das feiras
insert into storage.buckets (id, name, public)
values ('fairs', 'fairs', true)
on conflict (id) do update set public = true;

-- 2 atualizacao

insert into storage.buckets (id, name, public)
values ('fairs', 'fairs', true)
on conflict (id) do update set public = true;

-- 3 atualizacao

alter table public.fairs
add column if not exists cep text;

-- 4 atualizacao 

alter table public.fairs
add column if not exists cep text;

alter table public.fairs
add column if not exists photo_url text;

-- O admin usa a SUPABASE_SECRET_KEY no servidor Node.
-- Não crie políticas públicas para esta tabela.


-- 5 atualização: feiras em destaque na Home pública.
alter table public.fairs
  add column if not exists is_featured boolean not null default false;

create index if not exists fairs_featured_status_idx
  on public.fairs(is_featured, status);
