create table if not exists public.news_articles (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  category text not null default 'Portal das Feiras',
  author text not null default 'Redação',
  location text not null default 'Distrito Federal',
  excerpt text,
  content text not null,
  image_url text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists news_articles_status_idx on public.news_articles(status);
create index if not exists news_articles_published_at_idx on public.news_articles(published_at desc);
create index if not exists news_articles_category_idx on public.news_articles(category);
alter table public.news_articles add column if not exists author text not null default 'Redação';
alter table public.news_articles add column if not exists location text not null default 'Distrito Federal';

alter table public.news_articles enable row level security;

drop policy if exists news_articles_public_read on public.news_articles;
create policy news_articles_public_read on public.news_articles
for select using (status = 'published' and (published_at is null or published_at <= now()));

insert into storage.buckets (id, name, public)
values ('news', 'news', true)
on conflict (id) do update set public = true;
