create table if not exists public.sponsor_banners (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text not null,
  target_url text,
  status text not null default 'inactive'
    check (status in ('active', 'inactive')),
  display_order integer not null default 0,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists sponsor_banners_status_idx
on public.sponsor_banners(status);

create index if not exists sponsor_banners_order_idx
on public.sponsor_banners(display_order);

alter table public.sponsor_banners enable row level security;

drop policy if exists sponsor_banners_public_read
on public.sponsor_banners;

create policy sponsor_banners_public_read
on public.sponsor_banners
for select
using (
  status = 'active'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at >= now())
);

insert into storage.buckets (id, name, public)
values ('sponsors', 'sponsors', true)
on conflict (id) do update set public = true;


-- Controles avançados de exibição (migração segura para tabela já existente)
alter table public.sponsor_banners add column if not exists placement text not null default 'home_bottom';
alter table public.sponsor_banners add column if not exists campaign_group text not null default 'default';
alter table public.sponsor_banners add column if not exists display_mode text not null default 'fixed';
alter table public.sponsor_banners add column if not exists rotation_seconds integer not null default 8;

create index if not exists sponsor_banners_placement_idx
on public.sponsor_banners(placement);

create index if not exists sponsor_banners_group_idx
on public.sponsor_banners(campaign_group);
